[theme]
primaryColor="#4F46E5"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F3F4F6"
textColor="#111827"
font="sans serif"

[server]
enableXsrfProtection=true
enableCORS=true

[credentials]
[[credentials.users]]
username = "admin"
password = "admin123"

[[credentials.users]]
username = "user"
password = "user123"

[browser]
gatherUsageStats=false

[ui]
hideTopBar=false

[client]
toolbarMode="minimal"
showSidebarNavigation=false
